### ISSUE TITLE
Include querystring parameters in extras

### ISSUE THREAD

**Issue by richardszalay** [clayallsopp/routable-android#10]
It would be nice if querystring parameters were added as additional extras. This would allow additional, optional, parameters to be included.

Happy to do a PR

**Comment by clayallsopp** [comment]
I don't have a very strong opinion about it - if it can be done backwards compatibly, and with tests, then sounds good

**Comment by richardszalay** [comment]
Excellent. I don't see it introducing any backcompat issues.
