### ISSUE TITLE
Send extras bundle to RouterCallback

### ISSUE THREAD

**Issue by richardszalay** [clayallsopp/routable-android#9]
Extras aren't currently passed to RouterCallback so they get lost in the process.

Happy to do a PR for this, but it would break backwards compatibility  unless it introduced a RouterExtrasCallback, which smells bad. Thoughts?

**Comment by clayallsopp** [comment]
Aren't they passed as a `Map` argument? i.e.

```
Router.sharedRouter().map("logout", new Router.RouterCallback() {
    public void run(Map<String, String> extras) {
        User.logout();
    }
});
```

or am I misunderstanding the question?

**Comment by richardszalay** [comment]
Contrary to its name, the argument accepts route parameters, not extras. The open() method accepts `Bundle extras`, but those aren't passed to RouterCallback:

```java
	public void open(String url, Bundle extras, Context context) {
		if (context == null) {
			throw new ContextNotProvided(
					"You need to supply a context for Router "
							+ this.toString());
		}
		RouterParams params = this.paramsForUrl(url);
		RouterOptions options = params.routerOptions;
		if (options.getCallback() != null) {
			options.getCallback().run(params.openParams);
			return;
		}
```

**Comment by clayallsopp** [comment]
I see - I'm fine with breaking backwards compatibility in this case. I guess `run` should take both a `Map` for URL params, and a `Bundle` for extras?

**Comment by richardszalay** [comment]
Maybe we should change it to a single argument, RouteContext, which has properties for each of these things. Makes  backwards compatibility easier in the future. 

-----Original Message-----

**Comment by clayallsopp** [comment]
Yup I'd be cool with something like that too. Naming things is hard :)
